"""Python port of includes/translations.php — text stays identical, only the
language (PHP -> Python) has changed."""

LANGUAGES = {"en": "English", "ta": "தமிழ்", "hi": "हिन्दी", "ml": "മലയാളം"}


def formflow_translations():
    return {
        "en": {"name": "English", "home": "Home", "how": "How It Works", "services": "Services", "about": "About", "new": "New Analysis", "navigator": "Application Readiness & Journey Navigator", "choose": "Choose a service", "language": "Answer language", "question": "What would you like to know?", "analyze": "Check my readiness", "loading": "FormFlow AI is preparing your application journey...", "privacy": "Do not enter passwords, bank PINs, OTPs, or other highly sensitive information.", "answer": "FormFlow AI Answer", "journey": "Continue Your Journey", "next_question": "What would you like to know next?", "ask": "Ask FormFlow anything...", "send": "Ask", "official": "Official Application", "source": "Official Source", "source_label": "Source", "verified": "Last verified", "open": "Open Official Portal", "info": "View Official Information", "unavailable": "Official application link not currently verified. Please check the relevant authority website.", "next_action": "Your Next Action", "checklist": "My Application Checklist", "journey_map": "Application Journey", "new_action": "Start another readiness check", "based": "Based on your answers", "estimate": "FormFlow preparation estimate", "not_official": "This is not an official government, bank, or provider score.", "preparing": "Prepare with confidence", "answer_context": "Your question", "how_title": "What this means for your journey", "keep": "Keep Moving", "privacy_title": "Privacy", "service": "Service", "category": "Category", "language_label": "Language"},
        "ta": {"name": "தமிழ்", "home": "முகப்பு", "how": "எவ்வாறு செயல்படுகிறது", "services": "சேவைகள்", "about": "எங்களைப் பற்றி", "new": "புதிய பகுப்பாய்வு", "navigator": "விண்ணப்பத் தயார்நிலை மற்றும் பயண வழிகாட்டி", "choose": "ஒரு சேவையைத் தேர்ந்தெடுக்கவும்", "language": "பதில் மொழி", "question": "நீங்கள் எதைத் தெரிந்துகொள்ள விரும்புகிறீர்கள்?", "analyze": "என் தயார்நிலையைச் சரிபார்க்கவும்", "loading": "FormFlow AI உங்கள் விண்ணப்பப் பயணத்தைத் தயாரிக்கிறது...", "privacy": "கடவுச்சொல், வங்கி PIN, OTP அல்லது அதிக உணர்வுப்பூர்வமான தகவல்களை உள்ளிட வேண்டாம்.", "answer": "FormFlow AI பதில்", "journey": "உங்கள் விண்ணப்பப் பயணத்தைத் தொடருங்கள்", "next_question": "அடுத்து என்ன தெரிந்துகொள்ள விரும்புகிறீர்கள்?", "ask": "FormFlow-இடம் எதையும் கேளுங்கள்...", "send": "கேட்கவும்", "official": "அதிகாரப்பூர்வ விண்ணப்பம்", "source": "அதிகாரப்பூர்வ மூலம்", "source_label": "மூலம்", "verified": "கடைசியாக சரிபார்க்கப்பட்டது", "open": "அதிகாரப்பூர்வ தளத்தைத் திறக்கவும்", "info": "அதிகாரப்பூர்வ தகவலைப் பார்க்கவும்", "unavailable": "அதிகாரப்பூர்வ விண்ணப்ப இணைப்பு தற்போது சரிபார்க்கப்படவில்லை. தொடர்புடைய அதிகாரத்தின் தளத்தைப் பார்க்கவும்.", "next_action": "உங்கள் அடுத்த செயல்", "checklist": "எனது விண்ணப்பப் பட்டியல்", "journey_map": "விண்ணப்பப் பயணம்", "new_action": "புதிய தயார்நிலைச் சரிபார்ப்பைத் தொடங்கவும்", "based": "உங்கள் பதில்களின் அடிப்படையில்", "estimate": "FormFlow தயார்நிலை மதிப்பீடு", "not_official": "இது அரசு, வங்கி அல்லது சேவை வழங்குநரின் அதிகாரப்பூர்வ மதிப்பெண் அல்ல.", "preparing": "நம்பிக்கையுடன் தயாராகுங்கள்", "answer_context": "உங்கள் கேள்வி", "how_title": "உங்கள் பயணத்திற்கு இதன் பொருள்", "keep": "தொடர்ந்து செல்லுங்கள்", "privacy_title": "தனியுரிமை", "service": "சேவை", "category": "வகை", "language_label": "மொழி"},
        "hi": {"name": "हिन्दी", "home": "होम", "how": "यह कैसे काम करता है", "services": "सेवाएँ", "about": "हमारे बारे में", "new": "नया विश्लेषण", "navigator": "आवेदन तैयारी और यात्रा मार्गदर्शक", "choose": "सेवा चुनें", "language": "उत्तर की भाषा", "question": "आप क्या जानना चाहते हैं?", "analyze": "मेरी तैयारी जाँचें", "loading": "FormFlow AI आपकी आवेदन यात्रा तैयार कर रहा है...", "privacy": "पासवर्ड, बैंक PIN, OTP या अन्य संवेदनशील जानकारी दर्ज न करें।", "answer": "FormFlow AI उत्तर", "journey": "अपनी आवेदन यात्रा जारी रखें", "next_question": "आप आगे क्या जानना चाहते हैं?", "ask": "FormFlow से कुछ भी पूछें...", "send": "पूछें", "official": "आधिकारिक आवेदन", "source": "आधिकारिक स्रोत", "source_label": "स्रोत", "verified": "अंतिम सत्यापन", "open": "आधिकारिक पोर्टल खोलें", "info": "आधिकारिक जानकारी देखें", "unavailable": "आधिकारिक आवेदन लिंक अभी सत्यापित नहीं है। संबंधित प्राधिकरण की वेबसाइट देखें।", "next_action": "आपका अगला कार्य", "checklist": "मेरी आवेदन सूची", "journey_map": "आवेदन यात्रा", "new_action": "नई तैयारी जाँच शुरू करें", "based": "आपके उत्तरों के आधार पर", "estimate": "FormFlow तैयारी अनुमान", "not_official": "यह कोई आधिकारिक सरकारी, बैंक या सेवा प्रदाता का स्कोर नहीं है।", "preparing": "विश्वास के साथ तैयारी करें", "answer_context": "आपका प्रश्न", "how_title": "आपकी यात्रा के लिए इसका अर्थ", "keep": "आगे बढ़ें", "privacy_title": "गोपनीयता", "service": "सेवा", "category": "श्रेणी", "language_label": "भाषा"},
        "ml": {"name": "മലയാളം", "home": "ഹോം", "how": "എങ്ങനെ പ്രവർത്തിക്കുന്നു", "services": "സേവനങ്ങൾ", "about": "ഞങ്ങളെക്കുറിച്ച്", "new": "പുതിയ വിശകലനം", "navigator": "അപേക്ഷാ തയ്യാറെടുപ്പും യാത്രാ മാർഗ്ഗനിർദ്ദേശവും", "choose": "ഒരു സേവനം തിരഞ്ഞെടുക്കുക", "language": "ഉത്തരത്തിന്റെ ഭാഷ", "question": "നിങ്ങൾക്ക് എന്താണ് അറിയേണ്ടത്?", "analyze": "എന്റെ തയ്യാറെടുപ്പ് പരിശോധിക്കുക", "loading": "FormFlow AI നിങ്ങളുടെ അപേക്ഷാ യാത്ര തയ്യാറാക്കുന്നു...", "privacy": "പാസ്‌വേഡ്, ബാങ്ക് PIN, OTP അല്ലെങ്കിൽ മറ്റ് പ്രധാന സ്വകാര്യ വിവരങ്ങൾ നൽകരുത്.", "answer": "FormFlow AI ഉത്തരം", "journey": "നിങ്ങളുടെ അപേക്ഷാ യാത്ര തുടരുക", "next_question": "അടുത്തതായി എന്താണ് അറിയേണ്ടത്?", "ask": "FormFlow-നോട് എന്തും ചോദിക്കൂ...", "send": "ചോദിക്കുക", "official": "ഔദ്യോഗിക അപേക്ഷ", "source": "ഔദ്യോഗിക ഉറവിടം", "source_label": "ഉറവിടം", "verified": "അവസാനം പരിശോധിച്ചത്", "open": "ഔദ്യോഗിക പോർട്ടൽ തുറക്കുക", "info": "ഔദ്യോഗിക വിവരങ്ങൾ കാണുക", "unavailable": "ഔദ്യോഗിക അപേക്ഷാ ലിങ്ക് നിലവിൽ പരിശോധിച്ചിട്ടില്ല. ബന്ധപ്പെട്ട അധികാരിയുടെ വെബ്സൈറ്റ് പരിശോധിക്കുക.", "next_action": "നിങ്ങളുടെ അടുത്ത നടപടി", "checklist": "എന്റെ അപേക്ഷാ പട്ടിക", "journey_map": "അപേക്ഷാ യാത്ര", "new_action": "പുതിയ തയ്യാറെടുപ്പ് പരിശോധന ആരംഭിക്കുക", "based": "നിങ്ങളുടെ ഉത്തരങ്ങളുടെ അടിസ്ഥാനത്തിൽ", "estimate": "FormFlow തയ്യാറെടുപ്പ് കണക്ക്", "not_official": "ഇത് ഔദ്യോഗിക സർക്കാർ, ബാങ്ക് അല്ലെങ്കിൽ സേവനദാതാവിന്റെ സ്കോർ അല്ല.", "preparing": "ആത്മവിശ്വാസത്തോടെ തയ്യാറാകൂ", "answer_context": "നിങ്ങളുടെ ചോദ്യം", "how_title": "നിങ്ങളുടെ യാത്രയ്ക്ക് ഇതിന്റെ അർത്ഥം", "keep": "തുടരുക", "privacy_title": "സ്വകാര്യത", "service": "സേവനം", "category": "വിഭാഗം", "language_label": "ഭാഷ"},
    }


def formflow_language_code(value):
    mapping = {"English": "en", "Tamil": "ta", "Hindi": "hi", "Malayalam": "ml", "en": "en", "ta": "ta", "hi": "hi", "ml": "ml"}
    return mapping.get(value, "en")


def formflow_ui_extras():
    return {
        "en": {"back": "Back", "start": "Start your readiness check", "tell": "Tell us where you are", "current": "Your current position", "questions": "A few relevant questions", "clarify": "What would you like FormFlow to clarify?", "question_help": "Ask about documents, fields, submission, missing items, or future steps.", "journey_note": "Your application journey, organized.", "about_text": "FormFlow AI turns an uncertain application into a personalized readiness check, practical checklist, and clear next step.", "navigator": "Don\u2019t just understand the form. Know if you\u2019re ready to apply.", "privacy_text": "Do not enter passwords, bank PINs, OTPs, or other highly sensitive information.", "available": "READY / AVAILABLE", "prepare_status": "NEED TO PREPARE", "conditional": "CONDITIONAL / VERIFY", "ready_status": "READY TO PROCEED", "almost": "ALMOST READY", "needs": "NEEDS PREPARATION", "official_note": "Use the official authority channel to verify current requirements before submitting.", "understand": "Understand \u00b7 Prepare \u00b7 Apply", "prepare_stage": "Prepare", "apply_stage": "Apply", "verify_stage": "Verification", "processing": "Processing", "outcome": "Outcome", "next_stage": "Next Step", "follow": "Follow through", "what_next": "What happens next?", "documents": "What documents do I need?", "where_apply": "Where do I apply?", "custom_placeholder": "Type your next question...", "footer": "FormFlow AI \u00b7 Powered by Ollama & llama3.2:3b"},
        "ta": {"back": "பின்செல்", "start": "உங்கள் தயார்நிலைச் சரிபார்ப்பைத் தொடங்குங்கள்", "tell": "நீங்கள் எந்த நிலையில் இருக்கிறீர்கள்?", "current": "உங்கள் தற்போதைய நிலை", "questions": "சில தொடர்புடைய கேள்விகள்", "clarify": "FormFlow என்ன தெளிவுபடுத்த வேண்டும்?", "question_help": "ஆவணங்கள், புலங்கள், சமர்ப்பிப்பு அல்லது அடுத்த கட்டங்களைப் பற்றி கேளுங்கள்.", "journey_note": "உங்கள் விண்ணப்பப் பயணம் ஒழுங்குபடுத்தப்பட்டுள்ளது.", "about_text": "FormFlow AI உங்கள் தயார்நிலையைச் சரிபார்த்து, தனிப்பயன் பட்டியலையும் அடுத்த செயலையும் வழங்குகிறது.", "navigator": "படிவத்தை மட்டும் புரிந்துகொள்ளாதீர்கள். விண்ணப்பிக்கத் தயாரா என்பதை அறியுங்கள்.", "privacy_text": "கடவுச்சொல், வங்கி PIN, OTP அல்லது மிக முக்கியமான தனிப்பட்ட தகவல்களை உள்ளிட வேண்டாம்.", "available": "தயாராக உள்ளது", "prepare_status": "தயாரிக்க வேண்டும்", "conditional": "சரிபார்க்க வேண்டும்", "ready_status": "தொடரத் தயாராக உள்ளது", "almost": "கிட்டத்தட்ட தயாராக உள்ளது", "needs": "தயாரிப்பு தேவை", "official_note": "சமர்ப்பிப்பதற்கு முன் அதிகாரப்பூர்வ அதிகாரத்திடம் தற்போதைய தேவைகளைச் சரிபார்க்கவும்.", "understand": "புரிந்துகொள்ளுங்கள் \u00b7 தயாராகுங்கள் \u00b7 விண்ணப்பிக்கவும்", "prepare_stage": "தயாரிக்கவும்", "apply_stage": "விண்ணப்பிக்கவும்", "verify_stage": "சரிபார்ப்பு", "processing": "செயலாக்கம்", "outcome": "முடிவு", "next_stage": "அடுத்த கட்டம்", "follow": "தொடர்ந்து செல்லுங்கள்", "what_next": "அடுத்து என்ன நடக்கும்?", "documents": "என்ன ஆவணங்கள் தேவை?", "where_apply": "நான் எங்கு விண்ணப்பிக்கலாம்?", "custom_placeholder": "உங்கள் அடுத்த கேள்வியை உள்ளிடுங்கள்...", "footer": "FormFlow AI \u00b7 Ollama மற்றும் llama3.2:3b மூலம் இயக்கப்படுகிறது"},
        "hi": {"back": "वापस", "start": "अपनी तैयारी जाँच शुरू करें", "tell": "आप किस स्थिति में हैं?", "current": "आपकी वर्तमान स्थिति", "questions": "कुछ संबंधित प्रश्न", "clarify": "FormFlow क्या स्पष्ट करे?", "question_help": "दस्तावेज़, फ़ील्ड, जमा करने या अगले चरणों के बारे में पूछें।", "journey_note": "आपकी आवेदन यात्रा व्यवस्थित है।", "about_text": "FormFlow AI आपकी तैयारी जाँचकर व्यक्तिगत सूची और अगला कदम देता है।", "navigator": "सिर्फ फॉर्म न समझें। जानें कि आप आवेदन करने के लिए तैयार हैं या नहीं।", "privacy_text": "पासवर्ड, बैंक PIN, OTP या अत्यंत संवेदनशील व्यक्तिगत जानकारी दर्ज न करें।", "available": "उपलब्ध", "prepare_status": "तैयारी आवश्यक", "conditional": "सत्यापित करें", "ready_status": "आगे बढ़ने के लिए तैयार", "almost": "लगभग तैयार", "needs": "तैयारी आवश्यक", "official_note": "जमा करने से पहले संबंधित आधिकारिक प्राधिकरण से वर्तमान आवश्यकताएँ सत्यापित करें।", "understand": "समझें \u00b7 तैयारी करें \u00b7 आवेदन करें", "prepare_stage": "तैयारी", "apply_stage": "आवेदन", "verify_stage": "सत्यापन", "processing": "प्रक्रिया", "outcome": "परिणाम", "next_stage": "अगला चरण", "follow": "आगे बढ़ें", "what_next": "आवेदन के बाद क्या होगा?", "documents": "कौन से दस्तावेज़ चाहिए?", "where_apply": "मैं कहाँ आवेदन कर सकता हूँ?", "custom_placeholder": "अपना अगला प्रश्न लिखें...", "footer": "FormFlow AI \u00b7 Ollama और llama3.2:3b द्वारा संचालित"},
        "ml": {"back": "തിരികെ", "start": "നിങ്ങളുടെ തയ്യാറെടുപ്പ് പരിശോധിക്കുക", "tell": "നിങ്ങൾ ഏത് നിലയിലാണ്?", "current": "നിങ്ങളുടെ നിലവിലെ സ്ഥിതി", "questions": "ചില പ്രസക്തമായ ചോദ്യങ്ങൾ", "clarify": "FormFlow എന്താണ് വ്യക്തമാക്കേണ്ടത്?", "question_help": "രേഖകൾ, ഫീൽഡുകൾ, സമർപ്പിക്കൽ അല്ലെങ്കിൽ അടുത്ത ഘട്ടങ്ങളെക്കുറിച്ച് ചോദിക്കുക.", "journey_note": "നിങ്ങളുടെ അപേക്ഷാ യാത്ര ക്രമീകരിച്ചിരിക്കുന്നു.", "about_text": "FormFlow AI നിങ്ങളുടെ തയ്യാറെടുപ്പ് പരിശോധിച്ച് വ്യക്തിഗത പട്ടികയും അടുത്ത നടപടിയും നൽകുന്നു.", "navigator": "ഫോം മനസ്സിലാക്കുക മാത്രമല്ല. അപേക്ഷിക്കാൻ തയ്യാറാണോ എന്ന് അറിയുക.", "privacy_text": "പാസ്‌വേഡ്, ബാങ്ക് PIN, OTP അല്ലെങ്കിൽ വളരെ സ്വകാര്യമായ വിവരങ്ങൾ നൽകരുത്.", "available": "തയ്യാറാണ്", "prepare_status": "തയ്യാറാക്കണം", "conditional": "പരിശോധിക്കുക", "ready_status": "തുടരാൻ തയ്യാറാണ്", "almost": "ഏകദേശം തയ്യാറാണ്", "needs": "തയ്യാറെടുപ്പ് ആവശ്യമാണ്", "official_note": "സമർപ്പിക്കുന്നതിന് മുമ്പ് ബന്ധപ്പെട്ട ഔദ്യോഗിക അധികാരിയിൽ നിന്ന് നിലവിലെ ആവശ്യകതകൾ പരിശോധിക്കുക.", "understand": "മനസ്സിലാക്കുക \u00b7 തയ്യാറാക്കുക \u00b7 അപേക്ഷിക്കുക", "prepare_stage": "തയ്യാറാക്കുക", "apply_stage": "അപേക്ഷിക്കുക", "verify_stage": "പരിശോധന", "processing": "പ്രക്രിയ", "outcome": "ഫലം", "next_stage": "അടുത്ത ഘട്ടം", "follow": "തുടരുക", "what_next": "അപേക്ഷിച്ചതിന് ശേഷം എന്ത് സംഭവിക്കും?", "documents": "എന്തെല്ലാം രേഖകൾ വേണം?", "where_apply": "എവിടെയാണ് അപേക്ഷിക്കേണ്ടത്?", "custom_placeholder": "നിങ്ങളുടെ അടുത്ത ചോദ്യം എഴുതുക...", "footer": "FormFlow AI \u00b7 Ollamaയും llama3.2:3bയും ഉപയോഗിച്ച്"},
    }


def _dashboard_extras():
    return {
        "en": {"snapshot": "Preparation snapshot", "what_show": "What your answers show", "prepare_confidence": "Prepare with confidence", "from_prepare": "From prepare to next step", "guidance": "What this means for your journey", "missing_item": "Do not have an item?", "follow_question": "Follow-up question"},
        "ta": {"snapshot": "தயார்நிலைச் சுருக்கம்", "what_show": "உங்கள் பதில்கள் காட்டுவது", "prepare_confidence": "நம்பிக்கையுடன் தயாராகுங்கள்", "from_prepare": "தயாரிப்பிலிருந்து அடுத்த கட்டம்", "guidance": "உங்கள் பயணத்திற்கு இதன் பொருள்", "missing_item": "ஒரு பொருள் உங்களிடம் இல்லையா?", "follow_question": "தொடர் கேள்வி"},
        "hi": {"snapshot": "तैयारी का सारांश", "what_show": "आपके उत्तर क्या दिखाते हैं", "prepare_confidence": "विश्वास के साथ तैयारी करें", "from_prepare": "तैयारी से अगले चरण तक", "guidance": "आपकी यात्रा के लिए इसका अर्थ", "missing_item": "क्या कोई वस्तु आपके पास नहीं है?", "follow_question": "आगे का प्रश्न"},
        "ml": {"snapshot": "തയ്യാറെടുപ്പ് സംഗ്രഹം", "what_show": "നിങ്ങളുടെ ഉത്തരങ്ങൾ കാണിക്കുന്നത്", "prepare_confidence": "ആത്മവിശ്വാസത്തോടെ തയ്യാറാകൂ", "from_prepare": "തയ്യാറെടുപ്പിൽ നിന്ന് അടുത്ത ഘട്ടത്തിലേക്ക്", "guidance": "നിങ്ങളുടെ യാത്രയ്ക്ക് ഇതിന്റെ അർത്ഥം", "missing_item": "ഒരു ഇനം നിങ്ങളുടെ പക്കൽ ഇല്ലേ?", "follow_question": "തുടർ ചോദ്യം"},
    }


def t(key, language="en"):
    base = formflow_translations()
    extras = formflow_ui_extras()
    dashboard = _dashboard_extras()
    return (
        dashboard.get(language, {}).get(key)
        or extras.get(language, {}).get(key)
        or base.get(language, {}).get(key)
        or dashboard.get("en", {}).get(key)
        or extras.get("en", {}).get(key)
        or base.get("en", {}).get(key)
        or key
    )


WELCOME_CONTENT = {
    "en": {"title": "Welcome to FormFlow AI", "subtitle": "Your Application Readiness & Journey Navigator", "intro": "Get simple guidance for applications, certificates and important services.", "lead": "With FormFlow AI, you can:", "items": ["Understand what you need", "Prepare your documents and information", "Understand the application procedure", "Know what to do next", "Follow your application journey", "Download your personalized guide"], "apply": "I want to apply", "guidelines": "I need guidelines"},
    "ta": {"title": "வணக்கம்! FormFlow AI-க்கு வரவேற்கிறோம்", "subtitle": "உங்கள் விண்ணப்பத் தயார்நிலை மற்றும் பயண வழிகாட்டி", "intro": "விண்ணப்பங்கள், சான்றிதழ்கள் மற்றும் முக்கிய சேவைகளுக்கான எளிய வழிகாட்டுதலைப் பெறுங்கள்.", "lead": "FormFlow AI மூலம் நீங்கள்:", "items": ["என்ன தேவை என்பதை அறியலாம்", "தேவையான ஆவணங்களையும் தகவல்களையும் தயாரிக்கலாம்", "விண்ணப்ப செயல்முறையைப் புரிந்துகொள்ளலாம்", "அடுத்து என்ன செய்ய வேண்டும் என்பதை அறியலாம்", "உங்கள் விண்ணப்பப் பயணத்தைப் பின்தொடரலாம்", "தனிப்பயனாக்கப்பட்ட வழிகாட்டியைப் பதிவிறக்கலாம்"], "apply": "விண்ணப்பிக்க வேண்டும்", "guidelines": "வழிகாட்டுதல் வேண்டும்"},
    "hi": {"title": "FormFlow AI में आपका स्वागत है", "subtitle": "आपका आवेदन तैयारी और यात्रा मार्गदर्शक", "intro": "आवेदन, प्रमाणपत्र और महत्वपूर्ण सेवाओं के लिए सरल मार्गदर्शन पाएँ।", "lead": "FormFlow AI से आप:", "items": ["जान सकते हैं कि क्या चाहिए", "दस्तावेज़ और जानकारी तैयार कर सकते हैं", "आवेदन प्रक्रिया समझ सकते हैं", "जान सकते हैं कि आगे क्या करना है", "अपनी आवेदन यात्रा देख सकते हैं", "अपना व्यक्तिगत मार्गदर्शक डाउनलोड कर सकते हैं"], "apply": "मैं आवेदन करना चाहता हूँ", "guidelines": "मुझे मार्गदर्शन चाहिए"},
    "ml": {"title": "FormFlow AI-ലേക്ക് സ്വാഗതം", "subtitle": "നിങ്ങളുടെ അപേക്ഷാ തയ്യാറെടുപ്പും യാത്രാ മാർഗ്ഗനിർദ്ദേശവും", "intro": "അപേക്ഷകൾക്കും സർട്ടിഫിക്കറ്റുകൾക്കും പ്രധാന സേവനങ്ങൾക്കുമായി ലളിതമായ മാർഗ്ഗനിർദ്ദേശം നേടുക.", "lead": "FormFlow AI ഉപയോഗിച്ച് നിങ്ങൾക്ക്:", "items": ["എന്താണ് ആവശ്യമെന്ന് മനസ്സിലാക്കാം", "രേഖകളും വിവരങ്ങളും തയ്യാറാക്കാം", "അപേക്ഷാ നടപടിക്രമം മനസ്സിലാക്കാം", "അടുത്തതായി എന്ത് ചെയ്യണമെന്ന് അറിയാം", "നിങ്ങളുടെ അപേക്ഷാ യാത്ര പിന്തുടരാം", "വ്യക്തിഗത മാർഗ്ഗനിർദ്ദേശം ഡൗൺലോഡ് ചെയ്യാം"], "apply": "ഞാൻ അപേക്ഷിക്കണം", "guidelines": "എനിക്ക് മാർഗ്ഗനിർദ്ദേശം വേണം"},
}


def bank_ui_labels_js():
    """Mirrors the inline `bankUi` JS object built in index.php."""
    return {
        "en": {"bank": "Select your bank", "purpose": "What do you need?", "other": "Enter your bank name", "placeholder": "Search bank name or short name"},
        "ta": {"bank": "உங்கள் வங்கியைத் தேர்ந்தெடுக்கவும்", "purpose": "உங்களுக்கு என்ன தேவை?", "other": "உங்கள் வங்கியின் பெயரை உள்ளிடுங்கள்", "placeholder": "வங்கியின் பெயரைத் தேடுங்கள்"},
        "hi": {"bank": "अपना बैंक चुनें", "purpose": "आपको क्या चाहिए?", "other": "अपने बैंक का नाम लिखें", "placeholder": "बैंक का नाम खोजें"},
        "ml": {"bank": "നിങ്ങളുടെ ബാങ്ക് തിരഞ്ഞെടുക്കുക", "purpose": "നിങ്ങൾക്ക് എന്താണ് വേണ്ടത്?", "other": "നിങ്ങളുടെ ബാങ്കിന്റെ പേര് നൽകുക", "placeholder": "ബാങ്കിന്റെ പേര് തിരയുക"},
    }


def bank_ui_labels():
    """Mirrors the PHP `$bankUiLabels` array used server-side in analyze.php."""
    return {
        "en": {"bank": "Bank", "purpose": "Purpose"},
        "ta": {"bank": "வங்கி", "purpose": "தேவை"},
        "hi": {"bank": "बैंक", "purpose": "आवश्यकता"},
        "ml": {"bank": "ബാങ്ക്", "purpose": "ആവശ്യം"},
    }
